modfileVersion: "v1"
id: github.com/SENERGY-Platform/test-repo/mgw-module-2
name: Test Module 2
description: test 2
license: Apache-2.0 license
author: InfAI (CC SES)
version: v0.0.1
type: add-on
deploymentType: single
services:
  test-srv:
    name: Test Service 1
    image: nginxdemos/hello
    ports:
      - port: 80
    httpEndpoints:
      - name: Test
        extPath: "api"