modfileVersion: "v1"
id: github.com/SENERGY-Platform/test-repo/mgw-module
name: Test Module
description: test
license: Apache-2.0 license
author: InfAI (CC SES)
version: v0.0.1
type: add-on
deploymentType: single
services:
  manager:
    name: Test Service
    image: nginxdemos/hello
    httpEndpoints:
      - name: Test
        path: "/api"