modfileVersion: "v1"
id: github.com/SENERGY-Platform/test-repo/mgw-module
name: Test Module
description: test
license: Apache-2.0 license
author: InfAI (CC SES)
version: v0.0.3
type: add-on
deploymentType: single
services:
  manager:
    name: Test Service
    image: nginxdemos/hello
    ports:
      - port: 80
    httpEndpoints:
      - name: Test 1
        path: "/api1"
        extPath: "api1"
      - name: Test 2
        path: "/api2"
        extPath: "api2"