modfileVersion: "v1"
id: github.com/SENERGY-Platform/test-repo/mgw-module
name: Test Module
description: test
license: Apache-2.0 license
author: InfAI (CC SES)
version: v0.0.5
type: add-on
deploymentType: single
services:
  test-srv-1:
    name: Test Service 1
    image: nginxdemos/hello
    ports:
      - port: 80
    httpEndpoints:
      - name: Test 1
        path: "/api1"
        extPath: "api1"
      - name: Test 2
        path: "/api2"
        extPath: "api2"
  test-srv-2:
    name: Test Service 2
    image: nginxdemos/hello
    ports:
      - port: 80
    httpEndpoints:
      - name: Test
        path: "/test"
        extPath: "test"